apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envvar
  name: envvar
spec:
  containers:
  - image: busybox
    env:
      - name: NOM
        value: "Ghotra"
    name: envvar
    command: ['sh','-c','echo Hello $NOM']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
